version: "3"

services:
  catalog:
    build: ./catalog
    ports:
      - "3001:3001"
    volumes:
      - ./catalog/catalog.db:/app/catalog.db
    networks:
      - bazar-net

  order:
    build: ./order
    ports:
      - "3002:3002"
    depends_on:
      - catalog
    networks:
      - bazar-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - order
      - catalog
    networks:
      - bazar-net

networks:
  bazar-net:
    driver: bridge
